2019-09-02 09:38:39,589 - C:\Users\0923\Desktop\oa账号管理改版\SimulateLogIn\SimulateLogInLib\GetCookieStr.py[line:66] - ERROR: Message: element not interactable
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=70.0.3538.97 (d035916fe243477005bc95fe2a5778b8f20b6ae1),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "C:\Users\0923\Desktop\oa账号管理改版\SimulateLogIn\SimulateLogInLib\GetCookieStr.py", line 37, in get_cookie_str
    browser.find_element_by_id("profile-user-info-msg").click()
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not interactable
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=70.0.3538.97 (d035916fe243477005bc95fe2a5778b8f20b6ae1),platform=Windows NT 6.1.7601 SP1 x86_64)

2019-09-02 09:38:39,637 - C:\Users\0923\Desktop\oa账号管理改版\SimulateLogIn\SimulateLogInLib\SimulateLogIn.py[line:23] - ERROR: expected string or bytes-like object
Traceback (most recent call last):
  File "C:\Users\0923\Desktop\oa账号管理改版\SimulateLogIn\SimulateLogInLib\SimulateLogIn.py", line 19, in simulate_login
    resp = request.urlopen(req)
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1270, in _send_request
    self.putheader(hdr, value)
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1206, in putheader
    if _is_illegal_header_value(values[i]):
TypeError: expected string or bytes-like object
2019-09-02 09:38:39,642 - C:\Users\0923\Desktop\oa账号管理改版\SimulateLogIn\SimulateLogInLib\SimulateLogInConf.py[line:128] - ERROR: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\0923\Desktop\oa账号管理改版\SimulateLogIn\SimulateLogInLib\SimulateLogInConf.py", line 115, in simulate_login_conf_pass
    if SignIn in self.simulate_login():
TypeError: argument of type 'NoneType' is not iterable
2019-09-02 09:59:41,405 - C:\Users\0923\Desktop\oa账号管理改版\SimulateLogIn\SimulateLogInLib\GetCookieStr.py[line:66] - ERROR: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=70.0.3538.97 (d035916fe243477005bc95fe2a5778b8f20b6ae1),platform=Windows NT 6.1.7601 SP1 x86_64)
Traceback (most recent call last):
  File "C:\Users\0923\Desktop\oa账号管理改版\SimulateLogIn\SimulateLogInLib\GetCookieStr.py", line 35, in get_cookie_str
    browser.find_element_by_id("header-profile-button").click()
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=70.0.3538.97 (d035916fe243477005bc95fe2a5778b8f20b6ae1),platform=Windows NT 6.1.7601 SP1 x86_64)

2019-09-02 09:59:41,491 - C:\Users\0923\Desktop\oa账号管理改版\SimulateLogIn\SimulateLogInLib\SimulateLogIn.py[line:23] - ERROR: expected string or bytes-like object
Traceback (most recent call last):
  File "C:\Users\0923\Desktop\oa账号管理改版\SimulateLogIn\SimulateLogInLib\SimulateLogIn.py", line 19, in simulate_login
    resp = request.urlopen(req)
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1270, in _send_request
    self.putheader(hdr, value)
  File "C:\Users\0923\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1206, in putheader
    if _is_illegal_header_value(values[i]):
TypeError: expected string or bytes-like object
2019-09-02 09:59:41,500 - C:\Users\0923\Desktop\oa账号管理改版\SimulateLogIn\SimulateLogInLib\SimulateLogInConf.py[line:128] - ERROR: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Users\0923\Desktop\oa账号管理改版\SimulateLogIn\SimulateLogInLib\SimulateLogInConf.py", line 115, in simulate_login_conf_pass
    if SignIn in self.simulate_login():
TypeError: argument of type 'NoneType' is not iterable
